// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://miokxubbxkqzuhslgoah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pb2t4dWJieGtxenVoc2xnb2FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NjYwNTYsImV4cCI6MjA2NzU0MjA1Nn0.22l9lbLTrnUk0vwPrILvEh1RPWqTm-yo95C37n4MfkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});